services:
  - type: web
    name: media-downloader-bot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
    scaling:
      minInstances: 1
      maxInstances: 1
        sync: false  # Set this in Render dashboard
      - key: TWITTER_API_KEY_2
        sync: false  # Set this in Render dashboard
    healthCheckPath: /health
    autoDeploy: true
